version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:10.21
    container_name: prosting_db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:9.2.0
    container_name: prosting_pgadmin
    restart: always
    ports:
      - "5080:80"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  db_data:
  pgadmin_data: